image: docker:latest

stages:
  - build
  - test

build:
  stage: build
  script:
  - docker build -t users .

test:
  stage: test
  services:
  - arangodb
  script:
  - docker run -it -e $ARANGO_ROOT_PASSWORD users tox

variables:
  ARANGO_ROOT_PASSWORD: IXocx/FJV7jwVQ+DS0RagxeZiUD24Vlrp0LL6UpRfOHx
