stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
  - docker build -t registry.gitlab.com/project-alicia/users .

unit_test:
  stage: test
  script:
  - docker run -i -e ARANGO_ROOT_PASSWORD=$ARANGO_ROOT_PASSWORD registry.gitlab.com/project-alicia/users tox -c src/tox.ini -e dev

integration_test:
  stage: test
  script:
  - docker run --name arangodb -e ARANGO_ROOT_PASSWORD=$ARANGO_ROOT_PASSWORD arangodb
  - docker run --name redis redis
  - docker run -i -e ARANGO_ROOT_PASSWORD=$ARANGO_ROOT_PASSWORD --link arangodb --link redis registry.gitlab.com/project-alicia/users tox -c src/tox.ini -e stage
  only:
  - master

docker_push:
  stage: deploy
  script:
  - docker push registry.gitlab.com/project-alicia/users
  only:
  - master

deploy:
  stage: deploy
  script:
  - ansible-playbook -i hosts deploy.yml
  only:
  - master

variables:
  ARANGO_ROOT_PASSWORD: IXocx/FJV7jwVQ+DS0RagxeZiUD24Vlrp0LL6UpRfOHx
