stages:
  - build
  - test
  - docker_push
  - deploy

build:
  stage: build
  script:
  - docker build -t registry.gitlab.com/project-alicia/users .

test:
  stage: test
  script:
  - docker run -i -e ARANGO_ROOT_PASSWORD=$ARANGO_ROOT_PASSWORD registry.gitlab.com/project-alicia/users tox

docker_push:
  stage: docker_push
  script:
  - docker push registry.gitlab.com/project-alicia/users

deploy:
  stage: deploy
  script:
  - ansible-playbook deploy.yml
  only:
  - master

variables:
  ARANGO_ROOT_PASSWORD: IXocx/FJV7jwVQ+DS0RagxeZiUD24Vlrp0LL6UpRfOHx
