version: '2'
services:
  web:
    build: .
    env_file: .env
    image: users
    links:
    - arangodb
    ports:
    - 8000:8000
    volumes:
    - ./:/root
  arangodb:
    image: arangodb
    env_file: .env
    volumes:
    - /tmp/arangodb:/var/lib/arangodb3
