version: '2'
services:
  web:
    build: .
    env_file: .env
    image: users
    links:
    - mariadb
    ports:
    - 8000:8000
    volumes:
    - ./:/root
  mariadb:
    image: mariadb
    env_file: .env
