---
- name: create nginx location directory
  file: path=/etc/nginx/location/users.conf state=directory
- name: add nginx location config
  copy: src=nginx.conf dest=/etc/nginx/locations/users.conf
- name: start users docker container
  docker_container:
    env:
      ARANGO_ROOT_PASSWORD: IXocx/FJV7jwVQ+DS0RagxeZiUD24Vlrp0LL6UpRfOHx
    image: registry.gitlab.com/project-alicia/users
    name: users
    links:
    - arangodb
    - redis
    ports:
    - 8001:80
    state: started
